testing

diff --git a/.github/workflows/build_docs.yml b/.github/workflows/build_docs.yml
--- a/.github/workflows/build_docs.yml
+++ b/.github/workflows/build_docs.yml
@@ -62,6 +62,10 @@ jobs:
         run: |
             set -x
             set -e
+
+            touch /tmp/failed.txt
+            touch /tmp/succeeded.txt
+
             apt-get update
             DEBIAN_FRONTEND="noninteractive" apt-get install -y tzdata
             apt-get install -y git sudo
@@ -120,11 +124,15 @@ jobs:
             cat /usr/local/bin/runlinuxdocsquick
 
             git submodule foreach 'runlinuxdocsquick $name'
-            failed=$(wc -l /tmp/failed.txt)
-            succeeded=$(wc -l /tmp/succeeded.txt)
+
+            failed=$(wc -l /tmp/failed.txt | cut -d" " -f1)
+            succeeded=$(wc -l /tmp/succeeded.txt | cut -d" " -f1)
             echo "$failed failed, $succeeded succeeded."
             echo ""
             cat /tmp/failed.txt
+            if [ "$failed" != "0" ]; then
+                exit 1
+            fi
 
   macos:
     defaults:
@@ -152,6 +160,10 @@ jobs:
         run: |
             set -x
             set -e
+
+            touch /tmp/failed.txt
+            touch /tmp/succeeded.txt
+
             cp build_docs/macosdocs.sh /usr/local/bin/
 
             mkdir -p github/boostorg
@@ -204,11 +216,14 @@ jobs:
             cat /usr/local/bin/runmacosdocsquick
 
             git submodule foreach 'runmacosdocsquick $name'
-            failed=$(wc -l /tmp/failed.txt)
-            succeeded=$(wc -l /tmp/succeeded.txt)
+            failed=$(wc -l /tmp/failed.txt | cut -d" " -f1)
+            succeeded=$(wc -l /tmp/succeeded.txt | cut -d" " -f1)
             echo "$failed failed, $succeeded succeeded."
             echo ""
             cat /tmp/failed.txt
+            if [ "$failed" != "0" ]; then
+                exit 1
+            fi
 
   windows:
     strategy:
@@ -235,6 +250,9 @@ jobs:
       - name: docs
         shell: powershell
         run: |
+
+            echo $null >> C:\succeeded.txt
+            echo $null >> C:\failed.txt
 
             function Runwindowsdocs {
                 pwd
@@ -313,8 +331,15 @@ jobs:
 
             # For the rest --quick
             git submodule foreach 'powershell -command C:/scripts/cifunctions.ps1 $name'
-            echo "Succeeded:"
-            Get-Content C:\succeeded.txt | Measure-Object -Line
-            echo "Failed:"
-            Get-Content C:\failed.txt | Measure-Object -Line
+
+            $succeeded = Get-Content C:\succeeded.txt | Measure-Object -Line | Out-String
+            $failed = Get-Content C:\failed.txt | Measure-Object -Line | Out-String
+            echo "$failed failed, $succeeded succeeded."
+
             Get-Content C:\failed.txt
+
+            if ( $failed -ne '0' ) {
+                # what is the content of "failed"...
+                exit 1
+             }
+
